title: Team Hexagon
description: Team Hexagon Official Blog
author: Eojin Kim
team: Team Hexagon
logo: /static/img/teamLogo.png
github: https://github.com/KimEJ
about: Maker Team

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: Hexagon.Abyssal


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme: jekyll-theme-cayman
