title: Team Abyssal
description: Team Abyssal Official Blog
author: Eojin Kim
team: Team Abyssal
logo: /static/img/teamLogo.jpg
github: https://github.com/KimEJ
about: Maker Team

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: kimuj5090
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: Hexagon.Abyssal
  test: test


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme: jekyll-theme-cayman
